### PR TITLE
Fix standalone fast lossless build.

### LINKED ISSUE #2959: Fix standalone fast lossless build.
PR #2957 breaks the standalone fast lossless build.

This should be fixed by removing all the parts that need the internal libjxl library with the FJXL_STANDALONE macro.

### PR DESCRIPTION
**Pull request by szabadka**
Fixes #2959

### CODE REVIEW

File: lib/jxl/enc_fast_lossless.h [hunk 1]
```diff
@@ -18,10 +17,32 @@
...
+  void* opaque;
+  const void* (*get_color_channel_data_at)(void* opaque, size_t xpos,
+                                           size_t ypos, size_t xsize,
+                                           size_t ysize, size_t* row_offset);
+  void (*release_buffer)(void* opaque, const void* buf);
+};
+// The standalone version does not use this struct, but we define it here so
+// that we don't have to clutter all the function signatures with defines.
+struct JxlEncoderOutputProcessorWrapper {
+  int palceholder;
```
Comment (veluca93) [inline lib/jxl/enc_fast_lossless.h:42]: typo: placeholder

I assume this is not an empty struct b/c some ABI difference between C and C++? I'd probably rename it to `unused_` if so

**Review by veluca93 — DISMISSED** [review]

File: lib/jxl/enc_fast_lossless.h (hunk 1 above)
Comment (szabadka) [reply lib/jxl/enc_fast_lossless.h]: Yes, because of the ABI difference. I renamed it to unused.

**Review by veluca93 — APPROVED** [review]
