### PR TITLE
Fix #2581 in a different way

### LINKED ISSUE #2581: Losslessly recompressing JXL turns enum tags into ICC profiles
**Describe the bug**
~~Consider the conformance sample `animation_icos4d.jxl`. (Here, for convenience: [https://buzo.us/H.jxl](https://buzo.us/H.jxl)). 
Attempting to losslessly recompress it using `cjxl -d 0` appears to be taking the 8-bit pixel data from the original and encoding it losslessly as 32-bit float, which inflates the file size pretty dramatically.~~ Fixed by #2591 although the next issue remains, at the moment: 

It also seems to be embedding an ICC profile rather than tagging the new file with an sRGB enum, despite the original being tagged with an sRGB enum.

**To Reproduce**
```
$ cjxl -d 0 animation_icos4d.jxl test.jxl
$ jxlinfo -v animation_icos4.jxl
$ jxlinfo -v test.jxl
```

**Expected behavior**
I expected cjxl to preserve the tagged enum space rather than synthesize an ICC profile and then embed the synthesized profile.

**Log**
[https://buzo.us/D.log](https://buzo.us/D.log)

**Environment**
 - OS: Arch Linux x86_64
 - Compiler version: GCC 13
 - cjxl/djxl version string: JPEG XL encoder v0.9.0 00935aaa [AVX2]

### PR DESCRIPTION
**Pull request by sboukortt**
Always produce the ICC profile, but also indicate whether it’s the primary colorspace representation or not.

This lets `enc/jxl` ignore it if it’s not, and `enc/apng` include it for compatibility, helping with #2289.

### CODE REVIEW

File: lib/extras/packed_image.h [hunk 1]
```diff
@@ -244,9 +244,12 @@ class PackedPixelFile {
   std::vector<PackedExtraChannel> extra_channels_info;
 
   // Color information of the decoded pixels.
-  // If the icc is empty, the JxlColorEncoding should be used instead.
-  std::vector<uint8_t> icc;
+  enum {
+    kPreferColorEncoding,
+    kPreferIcc
+  } preferred_color_profile = kPreferColorEncoding;
```
Comment (jonsneyers) [inline lib/extras/packed_image.h:250]: Could you add a comment here to explain what this toggle means / how it is used in enc/dec?

I'm not sure if `preferred_color_profile` is the best name for this variable, maybe something like `primary_colorspace_description` could make sense, with the other one being a 'secondary' colorspace description which is supposed to approximate the primary colorspace description, but it's the primary one that is authoritative and takes precedence, and the secondary one is only used to maximize compatibility and/or in cases where the format does not support signaling the primary one.

Comment (sboukortt) [reply lib/extras/packed_image.h]: Thanks, something like this?

**Review by jonsneyers — APPROVED** [review]

File: lib/extras/packed_image.h (hunk 1 above)
Comment (jonsneyers) [reply lib/extras/packed_image.h]: LGTM!
