### PR TITLE
Always try non-streaming file reading for non PPM/PGM inputs.

### LINKED ISSUE #3403: Stream encoder fails on PFM
**Describe the bug**
Valid PFM files cannot be opened by the streaming encoder on Windows.

**To Reproduce**
Download: https://drive.google.com/file/d/17Sldh7liNN4FZDcjRnbncNlb7ZBbNKsd/view?usp=sharing
Run: `cjxl sun.pfm sun.jxl -d 0.1 -e 5 --modular=1 --container=1 --streaming_input --streaming_output -x color_space=RGB_D65_SRG_Per_Lin --intensity_target=65000`

**Expected behavior**
streaming input should work (since the encoding works without `--streaming_input`

**Screenshots**
````
cjxl G:\Temp\compression\sun.pfm "G:\Temp\compression\sun_d0.1_e5_i65k.jxl" -d 0.1 -e 5 --modular=1 --container=1 --streaming_input --streaming_output -x color_space=RGB_D65_SRG_Per_Lin --intensity_target=65000
JPEG XL encoder v0.10.2 e148959 [AVX2,SSE2]
PNM decoding failed.
````

**Environment**
Environment
OS: Win11
CPU type: IAMD Ryzen 7 6800HS Creator Edition x86_64
cjxl v10.0.2 from releases

### PR DESCRIPTION
**Pull request by szabadka**
This makes --streaming_input flag best effort and prints a warning if streaming file reading failed.

Fixes #3403

### CODE REVIEW

File: tools/cjxl_main.cc [hunk 1]
```diff
@@ -1044,20 +1044,24 @@ int main(int argc, char** argv) {
...
   double decode_mps = 0;
   size_t pixels = 0;
+  bool try_non_streaming = true;
   jxl::extras::ChunkedPNMDecoder pnm_dec;
   if (args.streaming_input) {
     auto dec = jxl::extras::ChunkedPNMDecoder::Init(args.file_in);
     if (!dec.ok()) {
-      std::cerr << "PNM decoding failed." << std::endl;
-      exit(EXIT_FAILURE);
+      std::cerr << "Warning PPM/PGM decoding failed, trying non-streaming mode."
```
Comment (veluca93) [inline tools/cjxl_main.cc:1052]: maybe "PPM/PGM streaming decoding failed"?

**Review by veluca93 — APPROVED** [review]

**Review by veluca93 — APPROVED** [review]
