### PR TITLE
don't try to write files when --disable_output

### LINKED ISSUE #2994: djxl crashes with JXL_ABORT on any input with --disable_output
**Describe the bug**
djxl crashes when using --disable_output. It does not crash when writing to PNG, and libjxl works fine.

**To Reproduce**
Run djxl on any input JXL file with --disable_output. Preferably a debug build.

**Expected behavior**
Decoded to pixels, with output discarded.

**Log**
```
~/libjxl/conformance/testcases/bike :) $ djxl -v --disable_output input.jxl 
JPEG XL decoder v0.10.0 9b82fa10 [AVX2]
Read 388268 compressed bytes.
./lib/extras/packed_image.h:86: JXL_ABORT: Unhandled JxlDataType
Illegal instruction (core dumped)
```
This is reproducible with any JXL file, so no sample needed.

**Environment**
 - OS: x86_64 Arch Linux
 - Compiler version: GCC 13.2.1
 - cjxl/djxl version string: JPEG XL decoder v0.10.0 9b82fa10 [AVX2]

### PR DESCRIPTION
**Pull request by mo271**
fixes #2994

### CODE REVIEW

File: tools/djxl_main.cc [hunk 1]
```diff
@@ -550,57 +550,63 @@ int main(int argc, const char* argv[]) {
...
-    if (encoder && args.use_sjpeg) {
-      encoder->SetOption("jpeg_encoder", "sjpeg");
-    }
-    jxl::extras::EncodedImage encoded_image;
-    if (encoder) {
-      if (!args.quiet) cmdline.VerbosePrintf(2, "Encoding decoded image\n");
-      if (!encoder->Encode(ppf, &encoded_image)) {
-        fprintf(stderr, "Encode failed\n");
-        return EXIT_FAILURE;
+      if (encoder) {
```
Comment (szabadka) [inline tools/djxl_main.cc:564]: Now we can get rid of all the if (encoder ... parts, because we would have exited early in line 532 otherwise

Comment (mo271) [reply tools/djxl_main.cc]: done, and I used `encoder` instead of `!filename_out.empty()` in the main if, they should be the same value at that point.
