### PR TITLE
fast_lossless: rename FastLosslessEncode

### LINKED ISSUE #1855: experimental/fast_lossless doesn't anon-namespace its BitWriter
I can't combine `libjxl/experimental/fast_lossless` and the `github.com/veluca93/fpnge` encoder code in the same program (e.g. to compare the two encoders' speeds), because both fjxl and fpnge declare `struct BitWriter` in the top-level namespace, with the same name (and both have a `Write(uint32_t, uint64_t)` method) but different field layout (see links below). Linking both of them leads to a crash, presumably because the fjxl code mistakenly calls the fpnge BitWriter or vice versa.

- https://github.com/libjxl/libjxl/blob/506714edaa3dd670133b9fe094d5efb94f6d0f6e/experimental/fast_lossless/fast_lossless.cc#L46
- https://github.com/veluca93/fpnge/blob/48020025e197318ab3c695903a4577e3d9565ddb/fpnge.cc#L374

I believe one solution would be to wrap a C++ "anonymous namespace" around all of `fast_lossless.cc` code except for the final `FastLosslessEncode` function.

@veluca93

### PR DESCRIPTION
**Pull request by nigeltao**
Adding a "Jxl" prefix disambiguates it when combining it with e.g. a fast PNG encoder or fast WebP encoder. Some lines were subsequently re-formatted to fit within 80 columns.

Also wrap an "extern C" around that function.

Also wrap an anonymous namespace around the implementation, so that the fjxl BitWriter doesn't conflict with e.g. fpnge's BitWriter.

Also fix some -Wunknown-pragmas and -Wsign-compare g++ warnings.

Fixes #1855

### CODE REVIEW

**Comment by nigeltao** [comment]
@veluca93

File: experimental/fast_lossless/fast_lossless.cc [hunk 1]
```diff
@@ -1297,7 +1299,9 @@ size_t LLEnc(const unsigned char* rgba, size_t width, size_t stride,
     PrepareDCGlobalPalette(onegroup, width, height, hcode, palette, pcolors,
                            &group_data[0][0]);
   }
+#ifdef __clang__
```
Comment (veluca93) [inline experimental/fast_lossless/fast_lossless.cc:1302]: I don't think this is the right #define - iirc gcc -fopenmp is a thing too.

File: experimental/fast_lossless/fast_lossless.cc [hunk 2]
```diff
@@ -1324,9 +1328,16 @@ size_t LLEnc(const unsigned char* rgba, size_t width, size_t stride,
   return writer.bytes_written;
 }
 
-size_t FastLosslessEncode(const unsigned char* rgba, size_t width,
-                          size_t stride, size_t height, size_t nb_chans,
-                          size_t bitdepth, int effort, unsigned char** output) {
+}  // namespace
+
+size_t JxlFastLosslessEncode(const unsigned char* rgba,
```
Comment (veluca93) [inline experimental/fast_lossless/fast_lossless.cc:1333]: doesn't this need an extern "C" too then?

File: experimental/fast_lossless/fast_lossless.cc (hunk 1 above)
Comment (nigeltao) [reply experimental/fast_lossless/fast_lossless.cc]: Changed to `#ifdef _OPENMP`.

File: experimental/fast_lossless/fast_lossless.cc (hunk 2 above)
Comment (nigeltao) [reply experimental/fast_lossless/fast_lossless.cc:1337]: Technically, I don't think it's necessary (https://stackoverflow.com/a/1380926). But I put an extern here too.

Comment (veluca93) [reply experimental/fast_lossless/fast_lossless.cc:1337]: uh, TIL. Still useful to have it for documentation and possible shenanigans.

**Review by veluca93 — APPROVED** [review]

**Review by veluca93 — APPROVED** [review]
