### PR TITLE
extra channels for decoding to png

### LINKED ISSUE #3407: djxl does not output extra channels for png
**Describe the bug**
--output_extra_channels does not work and only a single PNG is written

**To Reproduce**
djxl suz-multichannel-800px.jxl --output_extra_channels multichannel.png

suz-multichannel-800px jxl
**Environment**
 - OS: Windows 10
 - CPU type: x86_64
 - cjxl/djxl version string: JPEG XL decoder v0.10.2 e148959 [AVX2,SSE2]

### PR DESCRIPTION
**Pull request by mo271**
partially fixes #3407

### CODE REVIEW

File: lib/extras/enc/apng.cc [hunk 1]
```diff
@@ -440,6 +459,26 @@ Status APNGEncoder::EncodePackedPixelFileToAPNG(
   return true;
 }
 
+Status APNGEncoder::EncodeExtraChannelToPNG(const PackedImage& image,
+                                            size_t bits_per_sample,
+                                            std::vector<uint8_t>* bytes) const {
+  // Create a new PackedImage and move data from the original image
+  PackedImage moved_image(std::move(const_cast<PackedImage&>(image)));
```
Comment (szabadka) [inline lib/extras/enc/apng.cc:466]: Since PNG encoding is used in a few other places than cjxl, it might have surprising effects (currently or in the future) if the const & ppf loses its extra channels, so it might be better to copy here. Or alternatively one could add extra arguments to EncodePackedPixelFileToAPNG to select which extra channel/frame to include in the output PNG.

Comment (mo271) [reply lib/extras/enc/apng.cc]: I added extra arguments to `EncodePackedPixelFileToAPNG`.

**Review by szabadka — APPROVED** [review]
