### PR TITLE
fix default resampling in encode api

### LINKED ISSUE #1210: Setting JXL_ENC_FRAME_SETTING_RESAMPLING with its documented default value breaks encoding
**Describe the bug**
https://github.com/libjxl/libjxl/blob/ec7adc703541daad0b6b1ec8bde5cbe3a3bfcf7c/lib/include/jxl/encode.h#L100-L106

This matches its setter:

https://github.com/libjxl/libjxl/blob/ec7adc703541daad0b6b1ec8bde5cbe3a3bfcf7c/lib/jxl/encode.cc#L768

But according to the encoder itself, the default value is not -1, it's **0** according to enc_file.cc:

https://github.com/libjxl/libjxl/blob/ec7adc703541daad0b6b1ec8bde5cbe3a3bfcf7c/lib/jxl/enc_file.cc#L204-L208

or **1** if we check enc_params.h:

https://github.com/libjxl/libjxl/blob/ec7adc703541daad0b6b1ec8bde5cbe3a3bfcf7c/lib/jxl/enc_params.h#L248-L253

This means that if I try to set it, e.g. when extracting the value from an UI dialog, this happens:

https://github.com/libjxl/libjxl/blob/ec7adc703541daad0b6b1ec8bde5cbe3a3bfcf7c/lib/jxl/enc_frame.cc#L322-L324

**To Reproduce**

Just append this line here:

https://github.com/libjxl/libjxl/blob/ec7adc703541daad0b6b1ec8bde5cbe3a3bfcf7c/examples/encode_oneshot.cc#L186-L190

```cpp
JxlEncoderFrameSettingsSetOption(frameSettings,
                                         JXL_ENC_FRAME_SETTING_RESAMPLING,
                                         cfg->getInt("resampling", -1));
```

**Expected behavior**

Encoding succeeds.

**Screenshots**

imagen

**Environment**
 - OS: [e.g. Windows] Windows 10 21H2
 - Compiler version: [e.g. clang 11.0.1] MSVC 14.29.30133
 - CPU type: [e.g. x86_64] x86_64
 - cjxl/djxl version string: [e.g. cjxl [v0.3.7 | SIMD supported: SSE4,Scalar]] JPEG XL encoder v0.7.0 0.6.1 [AVX2,SSE4,SSSE3,Scalar]

**Additional context**

The only place where `JXL_ENC_FRAME_SETTING_RESAMPLING` is declared to be `-1` by default is here:

https://github.com/libjxl/libjxl/blob/ec7adc703541daad0b6b1ec8bde5cbe3a3bfcf7c/tools/cjxl_ng_main.cc#L526-L536

### PR DESCRIPTION
**Pull request by jonsneyers**
Fixes #1210 so it does the correct thing when setting resampling to -1 in the API.

### CODE REVIEW

File: lib/jxl/enc_params.h [hunk 1]
```diff
@@ -254,6 +254,19 @@ struct CompressParams {
   size_t ec_resampling = 1;
   // Skip the downsampling before encoding if this is true.
   bool already_downsampled = false;
+
+  void PostInit() {
+    if (resampling == 0) {
```
Comment (veluca93) [inline lib/jxl/enc_params.h:259]: why not "== 0 || == -1" and the C API just sets the value?

Can we add a test?

Comment (veluca93) [reply lib/jxl/enc_params.h:259]: We can make it signed too :)

As for tests: mostly that setting it to -1 works and doesn't crash/...

Comment (jonsneyers) [reply lib/jxl/enc_params.h]: Made it signed, and also made it -1 by default, because we claim in the documentation that -1 is the default but actually 1 was the default.

I don't think a separate test is needed now, because all the existing tests that don't explicitly change it will now have it set to -1.

**Review by veluca93 — APPROVED** [review]
