### PR TITLE
correct docstring for JxlDecoderGetBoxSizeRaw

### LINKED ISSUE #2022: JxlDecoderGetBoxSizeRaw documentation is incorrect
It actually returns the entire raw box size as the name suggests, including the 4 bytes of the box length, and the 4 bytes of the box type (at least using libjxl 0.7.0), vs. just the box content length as claimed.

So either the API documentation needs to be updated, or the implementation needs to change to match (breaking)...

### PR DESCRIPTION
**Pull request by mo271**
fixes #2022

### CODE REVIEW

File: lib/include/jxl/decode.h [hunk 1]
```diff
@@ -1359,15 +1359,14 @@ JXL_EXPORT JxlDecoderStatus JxlDecoderGetBoxType(JxlDecoder* dec,
...
- * bytes indicating "brob". This function gives the size of the data that will
- * be written in the output buffer when getting boxes in the default raw
- * compressed mode. When @ref JxlDecoderSetDecompressBoxes is enabled, the
- * return value of function does not change, and the decompressed size is not
- * known before it has already been decompressed and output.
+ * JXL_DEC_BOX event. This is the size of the contents, including the 4 bytes
+ * indicating the box size, and the 4 bytes indicating the type and optionally
+ * the 8 bytes indicating a the size (for extended boxes). This function gives
+ * the size of the data that will be written in the output buffer when getting
+ * boxes in the default raw compressed mode. When @ref
```
Comment (veluca93) [inline lib/include/jxl/decode.h:1366]: This seems false now, no?

Comment (mo271) [reply lib/include/jxl/decode.h]: yes, corrected it, please check

**Review by veluca93 — APPROVED** [review]
