### PR TITLE
Cap the number of reference properties to the # of extra channels.

### LINKED ISSUE #3324: cap `-E`/`--modular_nb_prev_channels` to the number of channels of the image
**Describe the bug**
`-E` increases the encoding time if the value of the argument is larger than the number of channels in the image.
As far as I understand, `-E` describes how many channels in the image will be looked at at a time in the input image.
It does not make sens for it to do more work when `-E` exceeds the number of input channels of the image.  

The outputs produced with different `-E` options are identical.

**To Reproduce**
```
time cjxl img.png -e 9 -d 0 --patches 1 --disable_output
JPEG XL encoder v0.10.0 bf2b7655 [AVX2]
Encoding [Modular, lossless, effort: 9]
Compressed to 2340.7 kB (2.774 bpp).
3000 x 2250, 0.106 MP/s [0.11, 0.11], 1 reps, 16 threads.
66.56user 0.89system 1:03.93elapsed 105%CPU (0avgtext+0avgdata 587916maxresident)k
0inputs+0outputs (0major+67501minor)pagefaults 0swaps

time cjxl img.png -e 9 -d 0 -E 3 --patches 1 --disable_output
JPEG XL encoder v0.10.0 bf2b7655 [AVX2]
Encoding [Modular, lossless, effort: 9]
Compressed to 2340.7 kB (2.774 bpp).
3000 x 2250, 0.076 MP/s [0.08, 0.08], 1 reps, 16 threads.
91.80user 1.07system 1:29.41elapsed 103%CPU (0avgtext+0avgdata 607396maxresident)k
0inputs+0outputs (0major+74815minor)pagefaults 0swaps

time cjxl img.png -e 9 -d 0 -E 11 --patches 1 --disable_output
JPEG XL encoder v0.10.0 bf2b7655 [AVX2]
Encoding [Modular, lossless, effort: 9]
Compressed to 2340.7 kB (2.774 bpp).
3000 x 2250, 0.040 MP/s [0.04, 0.04], 1 reps, 16 threads.
172.36user 0.86system 2:49.79elapsed 102%CPU (0avgtext+0avgdata 781596maxresident)k
0inputs+0outputs (0major+98965minor)pagefaults 0swaps
```
**Expected behavior**
`-E` should be capped to the number of channels in the input image so that it takes the same amount of time if it's larger

**Screenshots**
grayscale image, 1 channel: 
img

**Environment**
 - OS: Arch Linux
 - Compiler version: clang version 16.0.6
 - CPU type: x86_64 Ryzen 2700x
 - cjxl/djxl version string: cjxl v0.10.0 bf2b7655 [AVX2]

### PR DESCRIPTION
**Pull request by veluca93**
Fixes #3324.

### CODE REVIEW

File: lib/jxl/enc_modular.cc [hunk 1]
```diff
@@ -260,6 +260,9 @@ ModularFrameEncoder::ModularFrameEncoder(const FrameHeader& frame_header,
         prop_order.erase(prop_order.begin() + 1);
       }
     }
+    int max_properties = std::max<int>(
+        cparams_.options.max_properties,
+        frame_header.nonserialized_metadata->m.num_extra_channels + 2);
```
Comment (jonsneyers) [inline lib/jxl/enc_modular.cc:265]: I suppose a slightly better bound is possible in case the color channels are not modular encoded (then it would be -1 instead of +2)...

**Review by jonsneyers — DISMISSED** [review]

**Review by jonsneyers — APPROVED** [review]
