### PR TITLE
relax rendering intent check

### LINKED ISSUE #1973: JxlEncoderAddJPEGFrame() failed
**Describe the bug**
I'm transcoding a large (~1.3M) image dataset of JPEGs to JXL using the lossless transcoding. For 864 images I get the following error:

```
JPEG XL encoder v0.8.0 091b60e5 [AVX3,AVX2,SSE4,SSSE3,Unknown]                                                                                                                                                                   
Read JPEG image with 43279 bytes.
Encoding [Container | JPEG, lossless transcode, effort: 7 | JPEG reconstruction data], 
JxlEncoderAddJPEGFrame() failed.
EncodeImageJXL() failed.
```

running in verbose mode does not give any extra information. 

I've attached an example inside a zip file (in case github tries to mess with the image)

[n03476991_52119.zip](https://github.com/libjxl/libjxl/files/10230108/n03476991_52119.zip)

**To Reproduce**

```
cjxl --lossless_jpeg=1 n03476991_52119.JPEG ./test.jxl 
```
should reproduce the failure

**Expected behavior**
A JXL trancoding is produced

**Environment**
 - OS: Linux
 - Compiler version: n/a
 - CPU type: x86_64
 - cjxl/djxl version string: JPEG XL encoder v0.8.0 091b60e5 [AVX3,AVX2,SSE4,SSSE3,Unknown]

### PR DESCRIPTION
**Pull request by mo271**
Closes #1973.
Because there appear to be images with faulty rendering intent in their ICC profiles in the wild, we relax the check for valid rendering intent to a warning if we are able to deduce a plausible value for the rendering for the last byte of the rendering intent of the ICC profiles, i.e. the byte at offset 67, even if the other bytes (at offsets 64, 65 and 66) are non-zero. In that case we print a warning.

### CODE REVIEW

**Comment by sboukortt** [comment]
The fact that the profile that prompted this happens to contain `rendering intent = [0x01 0x00 0x00 0x00]` is a bit suspicious and gives the impression that the mistake was that the integer was encoded as little-endian instead of big-endian, suggesting that we should guess 1, not 0. How about trying both endiannesses instead?

**Comment by jonsneyers** [comment]
TIFF/Exif allow both endiannesses. I don't know the ICC specification, I guess it doesn't allow that? But I agree that this could be an endianness mistake.

**Comment by mo271** [comment]
Reading the ICC spec, it becomes clear that it doesn't allow little-endianness. 
So how to proceed here in case the byte at offset 64 is non-zero? I see two options when actually assuming that there was an endianness mistake during encoding,
1. ... and correct it and print a warning (this would mean rendering intent = 1 in the case of bug #1973)
2. ... print no warning
2. ... fail

I think 1. is the best option and will prepare a fix in that direction.

**Comment by jonsneyers** [comment]
Agreed that 1) is the best option.

File: lib/jxl/enc_color_management.cc [hunk 1]
```diff
@@ -887,11 +887,31 @@ Status ColorEncoding::SetFieldsFromICC() {
...
+    }
+    rendering_intent32 = icc_[64];
+    JXL_WARNING(
+        "Invalid rendering intent bytes: [0x%02X 0x%02X 0x%02X 0x%02X], "
+        "assuming %u was meant",
+        icc_[64], icc_[65], icc_[66], icc_[67], rendering_intent32);
+  }
+  uint32_t combined_rending_intent = rendering_intent32 + (icc_[66] << 8) +
+                                     (icc_[65] << 16) + (icc_[64] << 24);
+  if (combined_rending_intent > 3) {
```
Comment (sboukortt) [inline lib/jxl/enc_color_management.cc:914]: This is empty. Perhaps the similar check above could be moved here? Also, in the big endian case, `combined_rendering_intent` ends up with `icc_[64] + icc_[64] << 24` as far as I can tell.

Perhaps clearer would be to remove all this and just:

1. compute `big_endian_rendering_intent` from all four bytes (no “just take the last byte and check that the other bytes are zero” trick);
2. compute `little_endian_rendering_intent` from all four bytes in the other direction;
3. take the min and warn if that min is the little-endian version;
4. return an error if it’s more than 3.

What do you think?

**Review by sboukortt — CHANGES_REQUESTED** [review]

File: lib/jxl/enc_color_management.cc (hunk 1 above)
Comment (mo271) [reply lib/jxl/enc_color_management.cc:914]: I like that approach, will do it like this!

**Review by sboukortt — DISMISSED** [review]

File: lib/jxl/enc_color_management.cc [hunk 2]
```diff
@@ -887,14 +887,26 @@ Status ColorEncoding::SetFieldsFromICC() {
...
-      icc_[66] != 0) {
-    return JXL_FAILURE("Invalid rendering intent %u\n", rendering_intent32);
+  // should be encoded as big-endian 32-bit integer in bytes 60..63.
+  uint32_t big_endian_rendering_intent =
+      icc_[67] + (icc_[66] << 8) + (icc_[65] << 16) + (icc_[64] << 24);
+  // Some files encode rendering intent as little endian, which is not spec
+  // compliant. However we accept those with a warning.
+  uint32_t litte_endian_rendering_intent =
+      (icc_[67] << 24) + (icc_[66] << 16) + (icc_[65] << 8) + icc_[64];
+  uint32_t cand_rendering_intent =
```
[the remark this answers is not in the document]
Comment (mo271) [reply lib/jxl/enc_color_management.cc]: done

**Review by sboukortt — APPROVED** [review]

**Review by sboukortt — APPROVED** [review]
